### PR TITLE
Added timeout setting

### PR DESCRIPTION
**Pull request by lzap**
This needs https://github.com/govdelivery/infoblox/pull/59 first.

### CODE REVIEW

**Comment by ekohl** [comment]
Should this update the gem dependency as well to the latest so it's actually used? Currently it's not released yet though.

**Comment by ares** [comment]
blocked by https://github.com/govdelivery/infoblox/pull/59

**Comment by lzap** [comment]
BZ is: https://bugzilla.redhat.com/show_bug.cgi?id=1715999

**Comment by lzap** [comment]
For the record, this was not root cause of the issue, let's add this here and into DHCP module as well it won't hurt but it's not a priority now.

**Pull request merged**
